database_path: data/fetal_health.db
model_paths:
  Gradient Boosting: models/gradient_boosting_model.pkl
  Neural Network: models/neural_network_model.keras
  Random Forest: models/random_forest_model.pkl
  SVM: models/svm_model.pkl
scaler_path: models/data_scaler.pkl
